image: adoptopenjdk:17-jdk-hotspot

clone:
  depth: full  # Necessário para SonarCloud para atribuição correta dos problemas.

definitions:
  caches:
    gradle: ~/.gradle
    m2: ~/.m2
    sonar: ~/.sonar/cache  # Cache para o SonarCloud.

pipelines:
  default:
    - step:
        name: Build, Test, and Sonar Analysis
        caches:
          - gradle
          - m2
          - sonar
        script:
          # Conceder permissão de execução para o wrapper do Gradle
          - chmod +x ./gradlew

          # Executar tarefas do Gradle para construir, testar e analisar com SonarCloud
          - ./gradlew clean build sonarqube

        artifacts:
          - "build/libs/**/*.jar"
