image: openjdk:17-jdk-slim

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache

  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - gradle
          - sonar
        script:
          - chmod +x gradlew
          - ./gradlew build sonar
        artifacts:
          - build/libs/**
sonar:
  coverage:
    jacoco:
      xml: true
      html: true
      xmlreportPaths:
        - build/reports/jacoco/test/jacocoTestReport.xml

pipelines:
  branches:
    master:
      - step: *build-test-sonarcloud
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
