spring:
  application:
    name: eFurniture

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/efurniture
    username: admin
    password: funiture@Manager


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
    open-in-view: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    encoding: utf-8

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework: INFO
    org.hibernate: ERROR

server:
  port: 8080

info:
  app:
    name: 'eFurniture'
    description: 'Aplicação para gerenciamento de orçamentos de móveis planejados.'
    version: '1.0.0'
