amqp:
  admin:
    auto-create: true
  queues:
    email-confirmation:
      exchange: user.events
      routing-key: email.confirmation
      queue: email.confirmation.queue

spring:
  application:
    name: mobilplan
    url: http://localhost:8081
    email-validation-url: ${spring.application.url}/v1/usuarios/novo/confirmar-email
    waiting-time-to-confirm-email-in-minutes: 30

  repository:
    bucket-name:
      logomarca: logomarca
      avatar: avatar

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}/mobilplan
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  rabbitmq:
    dynamic: ${amqp.admin.auto-create}
    host: ${AMQP_RABBIT_HOST}
    port: ${AMQP_RABBIT_PORT}
    username: ${AMQP_RABBIT_USERNAME}
    password: ${AMQP_RABBIT_PASSWORD}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: false
    open-in-view: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}


  flyway:
    baseline-on-migrate: true
    enabled: false
    encoding: utf-8

  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NOREPLY_EMAIL}
    password: ${NOREPLY_EMAIL_PASS}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

jwt:
  secret: ${JWT_SECRET}

keycloak:
  realm: ${KEYCLOAK_REALM}
  host: ${KEYCLOAK_HOST}
  username: ${KEYCLOAK_USER}
  password: ${KEYCLOAK_ADMIN_CLI_PASS}

logging:
  level:
    org.springframework: INFO
    org.hibernate: ERROR

server:
  port: 8081

info:
  app:
    name: 'MobilPlan'
    description: 'Aplicação para gerenciamento de orçamentos de móveis planejados.'
    version: '1.0.0'

