# Configurações comuns a todos os perfis
info:
  app:
    name: 'Projeto Básico'
    description: 'Projeto básico com Spring Boot'
    version: '1.0.0'

---
# Configurações específicas para o perfil "producao"
spring:
  config:
    activate:
      on-profile: "prod"

---

# Configurações específicas para o perfil "dev"
spring:
  config:
    activate:
      on-profile: "dev"
