# Configurações comuns a todos os perfis
info:
  app:
    name: 'eFurniture'
    description: 'Aplicação para gerenciamento de orçamentos de móveis planejados.'
    version: '1.0.0'

# Configurações específicas para o perfil "test"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/efurniture
    username: admin
    password: funiture@Manager
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Postgre10SQLDialect


  flyway:
    baseline-on-migrate: true
    enabled: false
    encoding: utf-8
