# Configurações comuns a todos os perfis
info:
  app:
    name: 'Projeto Básico'
    description: 'Projeto básico com Spring Boot'
    version: '1.0.0'

---
# Configurações específicas para o perfil "dev"
spring:
  config:
    activate:
      on-profile: "prod"

---

# Configurações específicas para o perfil "dev"
spring:
  config:
    activate:
      on-profile: "dev"

---

# Configurações específicas para o perfil "test"
spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: '/h2-console'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
