spring:
  application:
    name: mobilplan

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mobilplan
    username: admin
    password: mobilplan@admin


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
    open-in-view: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    encoding: utf-8

  sql:
    init:
      mode: always

keycloack:
  realm: ${KEYCLOAK_REALM:jstec}
  host: ${KEYCLOAK_HOST:http://localhost:8080}

logging:
  level:
    org.springframework: INFO
    org.hibernate: ERROR

server:
  port: 8081

info:
  app:
    name: 'mobilplan'
    description: 'Aplicação para gerenciamento de orçamentos de móveis planejados.'
    version: '1.0.0'
